import type { ZineIssue } from "./zine";

// Generated by scripts/publish-ai-radar-zines.py. Do not edit by hand.
export const generatedZineIssues: ZineIssue[] = [
  {
    slug: "ai-radar-2026-06-19",
    title: "DestructoR666 AI Digest · 2026-06-19",
    kicker: "AI Radar // 2026-06-19",
    date: "2026-06-19",
    dek: "Signal Rag distilled 80 AI/agent leads into 50 articles/research/opinions, 30 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-19/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Show HN: AI Commander – TeamViewer for AI Agents, No VPN or SSH",
            summary: "A community-submitted project/thread. Plain version: Let Claude, Codex, ChatGPT, or any MCP/HTTP client run shell commands on machines you own.",
            whyItMatters: "Codex is turning into OpenAI’s agentic workbench. Worth tracking for cloud dev-env patterns, long-running task ergonomics, and places Hermes can stay lighter/local.",
            link: "https://aicommander.dev/",
            verdict: "read",
          },
          {
            title: "Is it agentic enough? Benchmarking open models on your own tooling",
            summary: "A post from Hugging Face Blog. Plain version: A source lead with no useful publisher summary. Use the title as the hook, then only open it if the topic matches today’s agent/tooling work: Is it agentic enough? Benchmarking open models on your own tooling.",
            whyItMatters: "Evals are how we avoid vibes-only agent work. Useful if it suggests tests we can adapt for Hermes/OAC reliability.",
            link: "https://huggingface.co/blog/is-it-agentic-enough",
            verdict: "skim",
          },
          {
            title: "Show HN: Sqim – install your iOS builds from Codex mobile without VPN",
            summary: "A community-submitted project/thread. Plain version: Sqim is a lightweight iOS app to preview your Swift builds on-the-go.",
            whyItMatters: "Codex is turning into OpenAI’s agentic workbench. Worth tracking for cloud dev-env patterns, long-running task ergonomics, and places Hermes can stay lighter/local.",
            link: "https://www.sqim.dev/",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-19/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-18",
    title: "DestructoR666 AI Digest · 2026-06-18",
    kicker: "AI Radar // 2026-06-18",
    date: "2026-06-18",
    dek: "Signal Rag distilled 80 AI/agent leads into 50 articles/research/opinions, 30 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-18/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Show HN: Automatiq - generate webscrapers/automations by browsing any website",
            summary: "A community-submitted project/thread. Plain version: A tool that watches you browse, then writes HTTP-based automation scripts - StoneSteel27/AutomatiQ",
            whyItMatters: "HN is noisy, but comments surface implementation pain fast. Good for spotting whether a shiny thing survives contact with engineers.",
            link: "https://github.com/StoneSteel27/AutomatiQ",
            verdict: "read",
          },
          {
            title: "Show HN: We cut >60% of tokens from agentic tasks by removing repeated context",
            summary: "A community-submitted project/thread. Plain version: Connect your databases, documents, Google Drive, Notion etc.",
            whyItMatters: "Directly relevant to context bloat and tool-loading discipline. If it is good, it may inform how Hermes/OAC keeps prompts lean.",
            link: "https://parcle.ai/",
            verdict: "skim",
          },
          {
            title: "Bad MCP design costs your agent 5x more tokens",
            summary: "A community-submitted project/thread. A source lead with no useful publisher summary. Use the title as the hook, then only open it if the topic matches today’s agent/tooling work: Bad MCP design costs your agent 5x more tokens. Treat it as an early smoke sign…",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://news.ycombinator.com/item?id=48407391",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-18/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-17",
    title: "DestructoR666 AI Digest · 2026-06-17",
    kicker: "AI Radar // 2026-06-17",
    date: "2026-06-17",
    dek: "Signal Rag distilled 80 AI/agent leads into 54 articles/research/opinions, 26 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-17/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Show HN: Ctx, save tokens by loading only the relevant tools",
            summary: "A community-submitted project/thread. Plain version: Skill, agent, MCP, and harness recommendations for Claude Code/custom LLMs: 102,928-node LLM-wiki graph, 91,464 skills, 467 agents, 10,790 MCPs, 207 harnesses, and capped execution recommendations.",
            whyItMatters: "Directly relevant to context bloat and tool-loading discipline. If it is good, it may inform how Hermes/OAC keeps prompts lean.",
            link: "https://github.com/stevesolun/ctx",
            verdict: "read",
          },
          {
            title: "Show HN: GitHits Public Beta 0.9",
            summary: "A community-submitted project/thread. Plain version: GitHits grounds AI coding agents in real open-source implementations so they stop guessing, avoid retry loops, and keep moving forward.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://githits.com/",
            verdict: "skim",
          },
          {
            title: "Show HN: InferBench – Benchmark local LLM engines with one click",
            summary: "A community-submitted project/thread. Plain version: Benchmark local LLM inference speed (tokens/sec) on your own hardware — llama.cpp native + cloud APIs, 124-model catalog, optimal-quant picker, and an MCP serve mode.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://github.com/JoniMartin27/inferbench",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-17/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-16",
    title: "DestructoR666 AI Digest · 2026-06-16",
    kicker: "AI Radar // 2026-06-16",
    date: "2026-06-16",
    dek: "Signal Rag distilled 80 AI/agent leads into 68 articles/research/opinions, 12 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-16/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Show HN: AwsmAudio – a WebAudio editor with native MCP",
            summary: "A community-submitted project/thread: AwsmAudio – a WebAudio editor with native MCP. Treat it as an early smoke signal, not a verdict. HN: 7 points, 0 comments. Query: AI agents tool use.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://audio.awsm.fun",
            verdict: "read",
          },
          {
            title: "Show HN: Kintsugi – a local-first safety net for AI agents and humans",
            summary: "A community-submitted project/thread: Kintsugi – a local-first safety net for AI agents and humans. Treat it as an early smoke signal, not a verdict. HN: 1 points, 0 comments. Query: MCP agent LLM.",
            whyItMatters: "This hits your preferred direction: agent workflows that keep state/recovery local instead of turning everything into SaaS vapor and regret.",
            link: "https://github.com/arrowassassin/kintsugi",
            verdict: "skim",
          },
          {
            title: "Show HN: BlitzGraph – Supabase for graphs, built for LLM agents",
            summary: "A community-submitted project/thread: BlitzGraph – Supabase for graphs, built for LLM agents. Treat it as an early smoke signal, not a verdict. HN: 2 points, 0 comments. Query: MCP agent LLM.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://blitzgraph.com",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-16/",
            verdict: "read",
          },
        ],
      },
    ],
  }
];
