import type { ZineIssue } from "./zine";

// Generated by scripts/publish-ai-radar-zines.py. Do not edit by hand.
export const generatedZineIssues: ZineIssue[] = [
  {
    slug: "ai-radar-2026-07-02",
    title: "DestructoR666 AI Digest · 2026-07-02",
    kicker: "AI Radar // 2026-07-02",
    date: "2026-07-02",
    dek: "Signal Rag distilled 80 AI/agent leads into 59 articles/research/opinions, 21 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-07-02/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Showcase Thursday - Drop your Hermes projects here.",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: Showcase Thursday — post your Hermes Agent builds, tools, workflows, and integrations.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1uldz1n/showcase_thursday_drop_your_hermes_projects_here/",
            verdict: "read",
          },
          {
            title: "Kilo Code vs. Hermes Agent",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: I vibe with Kilo & Minimax M3 in YOLO.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1ula0i3/kilo_code_vs_hermes_agent/",
            verdict: "skim",
          },
          {
            title: "Hermes Agent hosting",
            summary: "A Reddit field report/discussion from r/hermesagent. A title-first lead about: Hermes Agent hosting. Skim it only if that maps to current agent/tooling work. Treat it as user-signal and pain-report radar, not gospel.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1uleqpu/hermes_agent_hosting/",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-07-02/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-07-01",
    title: "DestructoR666 AI Digest · 2026-07-01",
    kicker: "AI Radar // 2026-07-01",
    date: "2026-07-01",
    dek: "Signal Rag distilled 80 AI/agent leads into 61 articles/research/opinions, 19 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-07-01/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "I gave my AI agents a shared memory via MCP — here's how",
            summary: "A Reddit field report/discussion from r/AI_Agents. Plain version: Jun 16, 2026 · A fair comparison would need an MCP agent (Hermes or Claude Code) ...",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/AI_Agents/comments/1u7ob9k/i_gave_my_ai_agents_a_shared_memory_via_mcp_heres/",
            verdict: "read",
          },
          {
            title: "attempting to create a self-auditing harness using openclaw/hermes",
            summary: "A Reddit field report/discussion from r/AI_Agents. Plain version: Apr 8, 2026 · hermes agent #1, \"the CTO\" - via cron job, scrapes github documentation changelog/issues DAILY + summarizes using local LLM model > switches to ...",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/AI_Agents/comments/1sfl9jy/attempting_to_create_a_selfauditing_harness_using/",
            verdict: "skim",
          },
          {
            title: "Distinct coding agent next to Hermes",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: I have Hermes running on a VPS and use it especially for coding.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1ukfq65/distinct_coding_agent_next_to_hermes/",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-07-01/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-30",
    title: "DestructoR666 AI Digest · 2026-06-30",
    kicker: "AI Radar // 2026-06-30",
    date: "2026-06-30",
    dek: "Signal Rag distilled 80 AI/agent leads into 54 articles/research/opinions, 26 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-30/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Herding Hermes' persistent memory: from self-hosting mem0 to EverOS",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: Been using Hermes for about half a year now, and memory has always been the thing that bugged me.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1ujfodk/herding_hermes_persistent_memory_from_selfhosting/",
            verdict: "read",
          },
          {
            title: "I set up Hermes Agent on a Raspberry Pi 5 and ended up with a small, practical local AI box",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: I wanted a lightweight, self-hosted assistant setup that was actually useful, not just a novelty install, so I put Hermes Agent on a Raspberry Pi 5 and kept the stack intentionally small.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1uje4d8/i_set_up_hermes_agent_on_a_raspberry_pi_5_and/",
            verdict: "skim",
          },
          {
            title: "Show HN: Reference MCP – let your AI agents search each other's past sessions",
            summary: "A community-submitted project/thread. A newly surfaced project/tool lead: let your AI agents search each other's past sessions Treat it as an early smoke signal, not a verdict. HN: 5 points, 0 comments. Query: Claude Code agent.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://github.com/kuberwastaken/reference",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-30/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-29",
    title: "DestructoR666 AI Digest · 2026-06-29",
    kicker: "AI Radar // 2026-06-29",
    date: "2026-06-29",
    dek: "Signal Rag distilled 80 AI/agent leads into 55 articles/research/opinions, 25 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-29/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "How to connect Hermes Agent to Arcade over MCP",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: Connecting AI agents such as Hermes to MCP Gateways makes it easier to manage multiple integrations.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1uikl1a/how_to_connect_hermes_agent_to_arcade_over_mcp/",
            verdict: "read",
          },
          {
            title: "Local Hermes set up need HELP",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: Hey everyone, I want to run Hermes locally on a Mac Mini and I’m looking for genuine feedback from people actually doing it right now.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1uil4z4/local_hermes_set_up_need_help/",
            verdict: "skim",
          },
          {
            title: "The AI Agent Setup That Finally Clicked for Me: Hermes + OpenAI Codex + Claude Code",
            summary: "A Reddit field report/discussion from r/hermesagent. A title-first lead about: The AI Agent Setup That Finally Clicked for Me: Hermes + OpenAI Codex + Claude Code. Skim it only if that maps to current agent/tooling work. Treat it as user-signal and pain-repor…",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1t9chdk/the_ai_agent_setup_that_finally_clicked_for_me/",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-29/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-28",
    title: "DestructoR666 AI Digest · 2026-06-28",
    kicker: "AI Radar // 2026-06-28",
    date: "2026-06-28",
    dek: "Signal Rag distilled 80 AI/agent leads into 65 articles/research/opinions, 15 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-28/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Anyone running Hermes on Mac Mini M4 24Gb Strictly Local LLM?",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: Shipping was delayed but FINALLY had delivery of my Mac Mini ordered months ago.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1uhkv7m/anyone_running_hermes_on_mac_mini_m4_24gb/",
            verdict: "read",
          },
          {
            title: "Kanban has so many foot guns.",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: It’s a great tool, but little chance that they sat down and user tested this properly (free and open source, I know, but still) Maybe this wouldn’t be an issue if it was called ‘execution que…",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1uhn5dz/kanban_has_so_many_foot_guns/",
            verdict: "skim",
          },
          {
            title: "Hermes now lets you stack frontier models into one virtual model. On Nous Research's own benchmark it beats Opus 4.8 and GPT-5.5.",
            summary: "A Reddit field report/discussion from r/hermesagent. A title-first lead about: Hermes now lets you stack frontier models into one virtual model. On Nous Research's own benchmark it beats Opus 4.8 and GPT-5.5.. Skim it only if that maps to current agent/toolin…",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1uhmabl/hermes_now_lets_you_stack_frontier_models_into/",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-28/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-27",
    title: "DestructoR666 AI Digest · 2026-06-27",
    kicker: "AI Radar // 2026-06-27",
    date: "2026-06-27",
    dek: "Signal Rag distilled 80 AI/agent leads into 54 articles/research/opinions, 26 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-27/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Show HN: Statey – the database your AI shares across every chat, over MCP",
            summary: "A community-submitted project/thread. A newly surfaced project/tool lead: the database your AI shares across every chat, over MCP Treat it as an early smoke signal, not a verdict. HN: 2 points, 2 comments. Query: AI agents tool use.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://www.statey.ai",
            verdict: "read",
          },
          {
            title: "Incident Report: CVE-2026-LGTM",
            summary: "A post from Simon Willison. Plain version: Incident Report: CVE-2026-LGTM Spectacular hypothetical incident report by Andrew Nesbitt.",
            whyItMatters: "Potentially useful for keeping your stack cheaper, more private, and less dependent on cloud APIs. Worth a skim if it looks practical.",
            link: "https://simonwillison.net/2026/Jun/26/incident-report/#atom-everything",
            verdict: "skim",
          },
          {
            title: "Can you honestly say Hermes Agent can do everything Claude Code ...",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: May 23, 2026 · Not out of the box, but it's possible for Hermes Agent to do everything if you give it the right tools and skills to be able to carry out tasks.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1tl1bhq/can_you_honestly_say_hermes_agent_can_do/",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-27/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-26",
    title: "DestructoR666 AI Digest · 2026-06-26",
    kicker: "AI Radar // 2026-06-26",
    date: "2026-06-26",
    dek: "Signal Rag distilled 80 AI/agent leads into 67 articles/research/opinions, 13 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-26/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Full Hermes Agent tutorial (Spanish with English auto-translation ...",
            summary: "A Reddit field report/discussion from r/AI_Agents. Plain version: May 20, 2026 · Full Hermes Agent tutorial (Spanish with English auto-translation).",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/AI_Agents/comments/1ths5g9/full_hermes_agent_tutorial_spanish_with_english/",
            verdict: "read",
          },
          {
            title: "OpenAI Agent SDK vs Hermes vs Pi vs OpenClaw : r/AI_Agents",
            summary: "A Reddit field report/discussion from r/AI_Agents. Plain version: 6 days ago · Pi and the OpenAI Agent SDK are pretty different things.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/AI_Agents/comments/1uas6nb/openai_agent_sdk_vs_hermes_vs_pi_vs_openclaw/",
            verdict: "skim",
          },
          {
            title: "Has anyone tried or considered trying a Hybrid architecture?",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: Have you guys tried the possibilty in the combined Architecture of Hermes+OpenClaw?",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://old.reddit.com/r/hermesagent/comments/1ugbqjo/has_anyone_tried_or_considered_trying_a_hybrid/",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-26/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-25",
    title: "DestructoR666 AI Digest · 2026-06-25",
    kicker: "AI Radar // 2026-06-25",
    date: "2026-06-25",
    dek: "Signal Rag distilled 80 AI/agent leads into 62 articles/research/opinions, 18 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-25/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Share integrations across Hermes, Codex and Claude Code",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: hey guys, how do you setup the mcp/cli connections across different harnesses and machines?",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1uf12u2/share_integrations_across_hermes_codex_and_claude/",
            verdict: "read",
          },
          {
            title: "I couldnt find a single self-hosted model on a 12gb GPU that could use an MCP server to get the temperature from home assistant",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: Per the title - anyone have a model that can do it?",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1uf0vbv/i_couldnt_find_a_single_selfhosted_model_on_a/",
            verdict: "skim",
          },
          {
            title: "Are harnesses like OpenClaw and Hermes really necessary?",
            summary: "A Reddit field report/discussion from r/LocalLLaMA. Plain version: May 12, 2026 · Agents like Hermes use tools to call Claude Code sesions for coding and you can pick the model for each session or task; It is as good as you ...",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/LocalLLaMA/comments/1tbgarl/are_harnesses_like_openclaw_and_hermes_really/",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-25/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-24",
    title: "DestructoR666 AI Digest · 2026-06-24",
    kicker: "AI Radar // 2026-06-24",
    date: "2026-06-24",
    dek: "Signal Rag distilled 76 AI/agent leads into 46 articles/research/opinions, 30 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-24/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "What are you guys using to make Hermes find what skills/MCPs are available for the task?",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: It's been great help for managing my workflows and I am constantly giving it new abilities to automate many of my life at this point.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1ue8ifd/what_are_you_guys_using_to_make_hermes_find_what/",
            verdict: "read",
          },
          {
            title: "I spent a week fighting Hermes' memory system. Here's what I built instead.",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: Set up Hermes Agent as my personal assistant.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1ue85ae/i_spent_a_week_fighting_hermes_memory_system/",
            verdict: "skim",
          },
          {
            title: "How can I generate images with Hermes?",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: I tried using ComfyUI, but Hermes said it wasn't possible due to several configuration errors that appeared.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1uebo9m/how_can_i_generate_images_with_hermes/",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-24/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-23",
    title: "DestructoR666 AI Digest · 2026-06-23",
    kicker: "AI Radar // 2026-06-23",
    date: "2026-06-23",
    dek: "Signal Rag distilled 68 AI/agent leads into 38 articles/research/opinions, 30 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-23/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Are you still enjoying hermes?",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: I know this is a biased question for this subreddit, but I want to know that, after some months, if Hermes still lives up to the hype.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1udctye/are_you_still_enjoying_hermes/",
            verdict: "read",
          },
          {
            title: "promptfoo got acquired by OpenAI. Langfuse got acquired by ClickHouse. The LLM eval space is consolidating into giants.",
            summary: "A Reddit field report/discussion from r/hermesagent. A title-first lead about: promptfoo got acquired by OpenAI. Langfuse got acquired by ClickHouse. The LLM eval space is consolidating into giants.. Skim it only if that maps to current agent/tooling work. Tr…",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1uddmp2/promptfoo_got_acquired_by_openai_langfuse_got/",
            verdict: "skim",
          },
          {
            title: "Has anyone created their own gateway?",
            summary: "A Reddit field report/discussion from r/hermesagent. Plain version: I’m seriously considering developing an internal use mobile first web app to communicate with Hermes from my phone.",
            whyItMatters: "Directly relevant to your agent stack. This can affect Hermes behavior, upgrade timing, plugins, gateway surfaces, or ideas worth stealing for OAC/DestructoR666.",
            link: "https://www.reddit.com/r/hermesagent/comments/1udfwcb/has_anyone_created_their_own_gateway/",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-23/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-22",
    title: "DestructoR666 AI Digest · 2026-06-22",
    kicker: "AI Radar // 2026-06-22",
    date: "2026-06-22",
    dek: "Signal Rag distilled 57 AI/agent leads into 27 articles/research/opinions, 30 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-22/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Show HN: Lockin – system-level distraction blocker controlled via text",
            summary: "A community-submitted project/thread. Plain version: Let AI block distractions for you when you need to lock in.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://www.lockinmcp.com",
            verdict: "read",
          },
          {
            title: "Samsung Electronics brings ChatGPT and Codex to employees",
            summary: "A post from OpenAI News. Plain version: Samsung Electronics deploys ChatGPT Enterprise and Codex to employees worldwide, marking one of OpenAI’s largest enterprise AI rollouts.",
            whyItMatters: "Codex is turning into OpenAI’s agentic workbench. Worth tracking for cloud dev-env patterns, long-running task ergonomics, and places Hermes can stay lighter/local.",
            link: "https://openai.com/index/samsung-electronics-chatgpt-codex-deployment",
            verdict: "skim",
          },
          {
            title: "Temporary Cloudflare Accounts for AI agents",
            summary: "A post from Simon Willison. Plain version: Temporary Cloudflare Accounts for AI agents The announcement says this is \"for AI agents\" but (as is pretty common these days) the AI hook isn't really necessary, this is an interesting feature for everyone el…",
            whyItMatters: "Kept because it matched the radar’s AI/agent/tooling filters. Skim title + source first; open only if it lines up with current Hermes/OAC work.",
            link: "https://simonwillison.net/2026/Jun/21/temporary-cloudflare-accounts/#atom-everything",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-22/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-21",
    title: "DestructoR666 AI Digest · 2026-06-21",
    kicker: "AI Radar // 2026-06-21",
    date: "2026-06-21",
    dek: "Signal Rag distilled 63 AI/agent leads into 33 articles/research/opinions, 30 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-21/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Show HN: Persona.js – a vanilla-JS agent UI library with native WebMCP (MIT)",
            summary: "A community-submitted project/thread. Plain version: Persona is an open-source, themeable AI chat widget you can add to any website in minutes.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://www.persona-chat.dev/",
            verdict: "read",
          },
          {
            title: "Just made an app and MCP Server to convert Markdown to Google Docs",
            summary: "A community-submitted project/thread. A title-first lead about: Just made an app and MCP Server to convert Markdown to Google Docs. Skim it only if that maps to current agent/tooling work. Treat it as an early smoke signal, not a verdict. HN: 2 points, 1 comm…",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://news.ycombinator.com/item?id=48601134",
            verdict: "skim",
          },
          {
            title: "Show HN: API Ingest – Agentic Search (Inter) API Docs",
            summary: "A community-submitted project/thread. Plain version: Handy MCP that converts API specs (OpenAPI YAML/JSON, RAML, WSDL, GraphQL, API Blueprint) into LLM-friendly markdown structures; focusing on token-efficiency and precision.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://github.com/mohidbt/api-ingest",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-21/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-20",
    title: "DestructoR666 AI Digest · 2026-06-20",
    kicker: "AI Radar // 2026-06-20",
    date: "2026-06-20",
    dek: "Signal Rag distilled 77 AI/agent leads into 47 articles/research/opinions, 30 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-20/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Show HN: CWC scans your Claude Code history and auto-builds agent workflows",
            summary: "A community-submitted project/thread. Plain version: Visual desktop app for composing multi-agent coding workflows.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://github.com/fayzan123/claude-workflow-composer",
            verdict: "read",
          },
          {
            title: "Quoting Sean Lynch",
            summary: "A post from Simon Willison. Plain version: The real valuable capability MCP offers over skills/CLI is isolating the auth flow outside of the agent’s context window, and potentially out of the harness completely.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://simonwillison.net/2026/Jun/19/sean-lynch/#atom-everything",
            verdict: "skim",
          },
          {
            title: "Show HN: Multiplayer Usage Tracking for Claude Code, Codex and OpenCode",
            summary: "A community-submitted project/thread. Plain version: Summer is a local, open-source tool for AI-coding usage and spend , built by Autumn .",
            whyItMatters: "Codex is turning into OpenAI’s agentic workbench. Worth tracking for cloud dev-env patterns, long-running task ergonomics, and places Hermes can stay lighter/local.",
            link: "https://github.com/useautumn/summer",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-20/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-19",
    title: "DestructoR666 AI Digest · 2026-06-19",
    kicker: "AI Radar // 2026-06-19",
    date: "2026-06-19",
    dek: "Signal Rag distilled 80 AI/agent leads into 50 articles/research/opinions, 30 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-19/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Show HN: AI Commander – TeamViewer for AI Agents, No VPN or SSH",
            summary: "A community-submitted project/thread. Plain version: Let Claude, Codex, ChatGPT, or any MCP/HTTP client run shell commands on machines you own.",
            whyItMatters: "Codex is turning into OpenAI’s agentic workbench. Worth tracking for cloud dev-env patterns, long-running task ergonomics, and places Hermes can stay lighter/local.",
            link: "https://aicommander.dev/",
            verdict: "read",
          },
          {
            title: "Is it agentic enough? Benchmarking open models on your own tooling",
            summary: "A post from Hugging Face Blog. Plain version: A title-first lead about: Is it agentic enough? Benchmarking open models on your own tooling. Skim it only if that maps to current agent/tooling work.",
            whyItMatters: "Evals are how we avoid vibes-only agent work. Useful if it suggests tests we can adapt for Hermes/OAC reliability.",
            link: "https://huggingface.co/blog/is-it-agentic-enough",
            verdict: "skim",
          },
          {
            title: "Show HN: Sqim – install your iOS builds from Codex mobile without VPN",
            summary: "A community-submitted project/thread. Plain version: Sqim is a lightweight iOS app to preview your Swift builds on-the-go.",
            whyItMatters: "Codex is turning into OpenAI’s agentic workbench. Worth tracking for cloud dev-env patterns, long-running task ergonomics, and places Hermes can stay lighter/local.",
            link: "https://www.sqim.dev/",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-19/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-18",
    title: "DestructoR666 AI Digest · 2026-06-18",
    kicker: "AI Radar // 2026-06-18",
    date: "2026-06-18",
    dek: "Signal Rag distilled 80 AI/agent leads into 50 articles/research/opinions, 30 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-18/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Show HN: Automatiq - generate webscrapers/automations by browsing any website",
            summary: "A community-submitted project/thread. Plain version: A tool that watches you browse, then writes HTTP-based automation scripts - StoneSteel27/AutomatiQ",
            whyItMatters: "HN is noisy, but comments surface implementation pain fast. Good for spotting whether a shiny thing survives contact with engineers.",
            link: "https://github.com/StoneSteel27/AutomatiQ",
            verdict: "read",
          },
          {
            title: "Show HN: We cut >60% of tokens from agentic tasks by removing repeated context",
            summary: "A community-submitted project/thread. Plain version: Connect your databases, documents, Google Drive, Notion etc.",
            whyItMatters: "Directly relevant to context bloat and tool-loading discipline. If it is good, it may inform how Hermes/OAC keeps prompts lean.",
            link: "https://parcle.ai/",
            verdict: "skim",
          },
          {
            title: "Bad MCP design costs your agent 5x more tokens",
            summary: "A community-submitted project/thread. A source lead with no useful publisher summary. Use the title as the hook, then only open it if the topic matches today’s agent/tooling work: Bad MCP design costs your agent 5x more tokens. Treat it as an early smoke sign…",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://news.ycombinator.com/item?id=48407391",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-18/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-17",
    title: "DestructoR666 AI Digest · 2026-06-17",
    kicker: "AI Radar // 2026-06-17",
    date: "2026-06-17",
    dek: "Signal Rag distilled 80 AI/agent leads into 54 articles/research/opinions, 26 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-17/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Show HN: Ctx, save tokens by loading only the relevant tools",
            summary: "A community-submitted project/thread. Plain version: Skill, agent, MCP, and harness recommendations for Claude Code/custom LLMs: 102,928-node LLM-wiki graph, 91,464 skills, 467 agents, 10,790 MCPs, 207 harnesses, and capped execution recommendations.",
            whyItMatters: "Directly relevant to context bloat and tool-loading discipline. If it is good, it may inform how Hermes/OAC keeps prompts lean.",
            link: "https://github.com/stevesolun/ctx",
            verdict: "read",
          },
          {
            title: "Show HN: GitHits Public Beta 0.9",
            summary: "A community-submitted project/thread. Plain version: GitHits grounds AI coding agents in real open-source implementations so they stop guessing, avoid retry loops, and keep moving forward.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://githits.com/",
            verdict: "skim",
          },
          {
            title: "Show HN: InferBench – Benchmark local LLM engines with one click",
            summary: "A community-submitted project/thread. Plain version: Benchmark local LLM inference speed (tokens/sec) on your own hardware — llama.cpp native + cloud APIs, 124-model catalog, optimal-quant picker, and an MCP serve mode.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://github.com/JoniMartin27/inferbench",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-17/",
            verdict: "read",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-radar-2026-06-16",
    title: "DestructoR666 AI Digest · 2026-06-16",
    kicker: "AI Radar // 2026-06-16",
    date: "2026-06-16",
    dek: "Signal Rag distilled 80 AI/agent leads into 68 articles/research/opinions, 12 releases/updates, radar stats, and collector logs.",
    href: "/zines/ai-radar-2026-06-16/",
    sections: [
      {
        label: "Editor picks",
        items: [
          {
            title: "Show HN: AwsmAudio – a WebAudio editor with native MCP",
            summary: "A community-submitted project/thread: AwsmAudio – a WebAudio editor with native MCP. Treat it as an early smoke signal, not a verdict. HN: 7 points, 0 comments. Query: AI agents tool use.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://audio.awsm.fun",
            verdict: "read",
          },
          {
            title: "Show HN: Kintsugi – a local-first safety net for AI agents and humans",
            summary: "A community-submitted project/thread: Kintsugi – a local-first safety net for AI agents and humans. Treat it as an early smoke signal, not a verdict. HN: 1 points, 0 comments. Query: MCP agent LLM.",
            whyItMatters: "This hits your preferred direction: agent workflows that keep state/recovery local instead of turning everything into SaaS vapor and regret.",
            link: "https://github.com/arrowassassin/kintsugi",
            verdict: "skim",
          },
          {
            title: "Show HN: BlitzGraph – Supabase for graphs, built for LLM agents",
            summary: "A community-submitted project/thread: BlitzGraph – Supabase for graphs, built for LLM agents. Treat it as an early smoke signal, not a verdict. HN: 2 points, 0 comments. Query: MCP agent LLM.",
            whyItMatters: "MCP is becoming the plumbing layer for agent tools. Worth watching because it shapes what Hermes/OAC can connect to without bespoke glue code.",
            link: "https://blitzgraph.com",
            verdict: "skim",
          },
        ],
      },
      {
        label: "Full issue",
        items: [
          {
            title: "Open the full hosted zine",
            summary: "The complete self-contained AI Radar HTML issue is published as a stable page on destructor666.com.",
            whyItMatters: "Daily digests should resolve to URLs, not raw HTML files in Telegram.",
            link: "/zines/ai-radar-2026-06-16/",
            verdict: "read",
          },
        ],
      },
    ],
  }
];
